function [mapName, relativePathToMapFile, found] = getBlockHelpMapNameAndPath(block_type)
%This function is for internal use only. It may be removed in the future.

% Returns the mapName and the relative path to the maps file for this
% block_type

% Copyright 2014-2016 The MathWorks, Inc.
    
blks = {... 
    'phased.Radiator'                               'phased_narrowband_transmit_array_block'        ;...
    'phased.internal.SimulinkReceiverPreamp'        'phased_receiver_preamp_block'                  ;...
    'phased.Transmitter'                            'phased_transmitter_block'                      ;...
    'phased.Collector'                              'phased_narrowband_receive_array_block'         ;...
    'phased.WidebandCollector'                      'phased_wideband_receive_array_block'           ;...
    'phased.FrostBeamformer'                        'phased_frost_beamformer_block'                 ;...
    'phased.LCMVBeamformer'                         'phased_lcmv_beamformer_block'                  ;...
    'phased.MVDRBeamformer'                         'phased_mvdr_beamformer_block'                  ;...
    'phased.PhaseShiftBeamformer'                   'phased_phase_shift_beamformer_block'           ;...
    'phased.SubbandPhaseShiftBeamformer'            'phased_subband_phase_shift_beamformer_block'   ;...
    'phased.TimeDelayBeamformer'                    'phased_time_delay_beamformer_block'            ;...
    'phased.TimeDelayLCMVBeamformer'                'phased_time_delay_lcmv_beamformer_block'       ;...
    'phased.CFARDetector'                           'phased_cfar_detector_block'                    ;...
    'phased.internal.SimulinkMatchedFilter'         'phased_matched_filter_block'                   ;...
    'phased.RangeResponse'                          'phased_range_response_block'                   ;...
    'phased.RangeDopplerResponse'                   'phased_range_doppler_response_block'           ;...
    'phased.StretchProcessor'                       'phased_stretch_processor_block'                ;...
    'phased.TimeVaryingGain'                        'phased_time_varying_gain_block'                ;...
    'phased.BeamscanEstimator'                      'phased_ula_beamscan_spectrum_block'            ;...
    'phased.BeamscanEstimator2D'                    'phased_beamscan_spectrum_block'                ;...
    'phased.BeamspaceESPRITEstimator'               'phased_beamspace_esprit_doa_block'             ;...
    'phased.ESPRITEstimator'                        'phased_esprit_doa_block'                       ;...
    'phased.MVDREstimator'                          'phased_ula_mvdr_spectrum_block'                ;...
    'phased.MVDREstimator2D'                        'phased_mvdr_spectrum_block'                    ;...
    'phased.RootMUSICEstimator'                     'phased_root_music_doa_block'                   ;...
    'phased.RootWSFEstimator'                       'phased_root_wsf_doa_block'                     ;...
    'phased.SumDifferenceMonopulseTracker'          'phased_ula_sum_diff_monopulse_block'           ;...
    'phased.SumDifferenceMonopulseTracker2D'        'phased_ura_sum_diff_monopulse_block'           ;...
    'phased.FreeSpace'                              'phased_free_space_block'                       ;...
    'phased.RadarTarget'                            'phased_radar_target_block'                     ;...
    'phased.internal.SimulinkBarrageJammer'         'phased_barrage_jammer_block'                   ;...
    'phased.internal.SimulinkConstantGammaClutter'  'phased_constant_gamma_clutter_block'           ;...
    'phased.gpu.ConstantGammaClutter'               'phased_constant_gamma_clutter_gpu_block'       ;...
    'phased.internal.SimulinkPlatform'              'phased_platform_motion_block'                  ;...
    'phased.internal.RangeAngle'                    'phased_rangeangle_block'                       ;...
    'phased.ADPCACanceller'                         'phased_adpca_canceller_block'                  ;...
    'phased.AngleDopplerResponse'                   'phased_angle_doppler_response_block'           ;...
    'phased.DPCACanceller'                          'phased_dpca_canceller_block'                   ;...
    'phased.STAPSMIBeamformer'                      'phased_stap_smi_beamformer_block'              ;...
    'phased.FMCWWaveform'                           'phased_fmcw_waveform_block'                    ;...
    'phased.internal.SimulinkLinearFMWaveform'      'phased_linear_fm_waveform_block'               ;...
    'phased.internal.SimulinkPhaseCodedWaveform'    'phased_phase_coded_waveform_block'             ;...
    'phased.internal.SimulinkRectangularWaveform'   'phased_rectangular_waveform_block'             ;...
    'phased.internal.SimulinkSteppedFMWaveform'     'phased_stepped_fm_waveform_block'              ;...
    'phased.MFSKWaveform'                           'phased_mfsk_waveform_block'                    ;...
    'phased.GCCEstimator'                           'phased_gcc_estimator_block'                    ;...
    'phased.WidebandFreeSpace'                      'phased_wideband_free_space_block'              ;...
    'phased.SubbandMVDRBeamformer'                  'phased_subband_mvdr_beamformer_block'          ;...
    'phased.WidebandRadiator'                       'phased_wideband_radiator_block'                ;...
    'phased.TwoRayChannel'                          'phased_two_ray_channel_block'                  ;...
    'phased.BackscatterRadarTarget'                 'phased_backscatter_radar_target_block'         ;...
    'phased.LOSChannel'                             'phased_los_channel_block'                      ;...
    'phased.WidebandLOSChannel'                     'phased_wideband_los_channel_block'             ;...
    'phased.WidebandTwoRayChannel'                  'phased_wideband_two_ray_channel_block'         ;...
    'phased.WidebandBackscatterRadarTarget'         'phased_wideband_backscatter_radar_target_block';...
    'phased.GSCBeamformer'                          'phased_gsc_beamformer_block'                   ;...
    'phased.CFARDetector2D'                         'phased_matrix_cfar_detector_block'             ;...
    'phased.MUSICEstimator'                         'phased_ula_music_spectrum_block'               ;...
    'phased.MUSICEstimator2D'                       'phased_music_spectrum_block'                   ;...
    'phased.RangeEstimator'                         'phased_range_estimator_block'                  ;...
    'phased.DopplerEstimator'                       'phased_doppler_estimator_block'                ;...
    'phased.ScatteringMIMOChannel'                  'phased_spatial_mimo_channel_block'             ;...
    'phased.internal.SimulinkPulseWaveformLibrary'  'phased_pulse_waveform_library_block'           ;...
    'phased.PulseCompressionLibrary'                'phased_pulse_compression_library_block'        ;...
    'phased.RangeAngleResponse'                     'phased_range_angle_response_block'             ;...
    'phased.MonopulseFeed'                          'phased_monopulse_feed_block'                   ;...
    'phased.MonopulseEstimator'                     'phased_monopulse_estimator_block'              ;...
    'Dechirp'                                       'phased_dechirp_block'                          ;...
    'Pulse Integrator'                              'phased_pulsint_block'                          ;...
    'Azimuth/broadside converter'                   'phased_azimuth_broadside_conv_block'           ;...
    'Data Cube Slicer'                              'phased_cube_slicer_block'                      ;...
};

relativePathToMapFile = '/phased/helptargets.map';

% See whether or not the block is a Phased Array System Toolbox block
idx = strcmp(block_type, blks(:,1));

if ~any(idx)
    found = false;
    mapName = 'User Defined';
else
    found = true;
    mapName = blks(idx,2);
end

